services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: outfique_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: outfique
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d outfique"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
