services:

  db:
    image: postgres:16-alpine
    restart: always
    container_name: outfique_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: outfique
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d outfique"]
      interval: 5s
      timeout: 5s
      retries: 5
  app: 
    build:
      context: .
      target: dev
    container_name: outfique_app
    command: sh -c "npx prisma migrate deploy && pnpm dev"

    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
       - DATABASE_URL=postgresql://user:secret@db:5432/outfique
    depends_on:
        db:
          condition: service_healthy


volumes:
  postgres_data:
