name: CI/CD Pipeline
on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/outfique-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/outfique-app:${{ github.sha }}
          target: prod
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure Docker daemon is running
            echo "Starting Docker daemon..."
            sudo systemctl start docker
            sudo systemctl enable docker

            # Create project directory and clone if needed
            if [ ! -d "/home/${{ secrets.EC2_USER }}/outfique" ]; then
              echo "Cloning repository..."
              cd /home/${{ secrets.EC2_USER }}
              git clone https://github.com/one-project-one-month/Outfique-backend.git outfique
            fi

            # Navigate to project directory
            cd /home/${{ secrets.EC2_USER }}/outfique

            # Pull latest deployment configuration
            echo "Pulling latest code..."
            git pull origin main

            # Pull the latest Docker image
            echo "Pulling latest Docker image..."
            sudo docker compose pull

            # Stop and remove old containers
            echo "Stopping old containers..."
            sudo docker compose down --remove-orphans

            # Start new containers
            echo "Starting new containers..."
            sudo docker compose -f docker-compose.dev.yml up -d

            # Show container status
            echo "Container status:"
            sudo docker compose ps
