name: PR Checks

on:
  pull_request:
    branches: [dev, main]

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up pnpm package manager
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint

      - name: Type check
        run: pnpm run type-check

      - name: Build check
        run: pnpm run build

      - name: Security audit
        run: pnpm audit --audit-level=moderate
